hydra:
  job:
    chdir: True
  run:
    dir: outputs/ground_truth_upper_bound/only_unet_sd1_5/${now:%Y-%m-%d__%H-%M-%S}

_target_: config.TrainerConfig

eval_script:
    _target_: config.EvalConfig
    images_dir: "/teamspace/studios/this_studio/outputs/2024-05-14__22-50-48/single_frame_exp_2_350epochs/predictions/epoch_0_step_0.png"
    evaluate: True

mapper:
  _target_: config.MapperConfig
  in_channels: 768
  hidden_channels: [2, 768]
  norm_layer_type: "layernorm"
  activation_layer_type: "relu"
  inplace: null
  bias: True
  dropout: 0.2
  train: False

lr:
  _target_: config.LearningRateConfig
  unet: 1e-4
  controlnet: 1e-4
  mapper: 1e-4
  scale: True

lr_scheduler:
  _target_: config.LRSchedulerConfig
  scheduler_type: "constant"
  warmup_steps: 500
  num_cycles: 1
  power: 1.0

optimizer:
  _target_: config.OptimizerConfig
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1e-2
  adam_epsilon: 1e-08

dataset:
  _target_: config.DatasetConfig
  dataset_name: "uavid"
  dataset_path: "/teamspace/studios/this_studio/uavid"
  resolution: 512
  center_crop: True
  max_previous_frames: 1 # null
  oracle: True

dataloader:
  _target_: config.DataloaderConfig
  train_batch_size: 6
  val_batch_size: 4
  num_workers: 4

model:
  _target_: config.ModelConfig
  model_name: "runwayml/stable-diffusion-v1-5" # "lambdalabs/sd-image-variations-diffusers"
  model_revision: null # "v2.0"
  image_encoder_name: "lambdalabs/sd-image-variations-diffusers"
  image_encoder_revision: "v2.0"
  train_unet: True
  train_control_net: False
  use_control_net: False
  lora_rank: 4
  use_ip_adapter: False
  ip_adapter_scale: 0.8
  use_mapper: False

gradient_accumulation_steps: 1
num_train_epochs: 350
max_train_steps: null
resume_from_checkpoint: "/teamspace/studios/this_studio/outputs/ground_truth_upper_bound/mlp/mapper_only2024-05-20__23-33-59/checkpoints/checkpoint_2"
checkpointing_steps: 500
checkpoints_total_limit: null
prediction_steps: 100
predictions_dir_name: "predictions"

max_grad_norm: 1.0

output_dir: "."
local_rank: -1

num_processes: 1

logging_dir_name: "logs"
allow_tf32: False
logger: "tensorboard"

overrode_max_train_steps: False