hydra:
  job:
    chdir: True
  run:
    dir: "outputs/test/${now:%Y-%m-%d__%H-%M-%S}/"
_target_: config.TrainerConfig

mapper:
  _target_: config.MapperConfig
  in_channels: 768
  hidden_channels: [256, 768]
  norm_layer_type: "layernorm"
  activation_layer_type: "relu"
  inplace: null
  bias: True
  dropout: 0.2
  train: False

lstm:
  _target_: config.LSTMConfig
  input_size: 768
  hidden_size: 768
  num_layers: 1
  bias: True
  batch_first: False
  dropout: 0.2
  bidirectional: False
  proj_size: 0
  train: True

dataset:
  _target_: config.DatasetConfig
  dataset_name: "uavid"
  dataset_path: "/teamspace/studios/this_studio/uavid"
  resolution: 512
  center_crop: True
  max_previous_frames: null
  oracle: False

dataloader:
  _target_: config.DataloaderConfig
  val_batch_size: 4
  num_workers: 4

model:
  _target_: config.ModelConfig
  model_name: "lambdalabs/sd-image-variations-diffusers" # "runwayml/stable-diffusion-v1-5"
  model_revision: "v2.0"
  image_encoder_name: "lambdalabs/sd-image-variations-diffusers" # "openai/clip-vit-large-patch14"
  image_encoder_revision: "v2.0"
  use_control_net: True
  lora_rank: 4
  use_ip_adapter: True
  ip_adapter_scale: 0.8
  use_mapper: False
  use_lstm: True
  use_img2img_inference: False
  use_img2img_refinement: False


use_custom_inference: False
guidance_scale: 2

use_checkpoint: /teamspace/studios/this_studio/outputs/fixed/LSTM/2024-06-14__12-55-43/checkpoints/checkpoint_5
output_dir: "."
local_rank: -1

num_processes: 1

allow_tf32: False
