hydra:
  job:
    chdir: True
  run:
    dir: outputs_sdft/${now:%Y-%m-%d__%H-%M-%S}

_target_: config.TrainerConfig

eval_script:
    _target_: config.EvalConfig
    images_path: "/teamspace/studios/this_studio/outputs/fixed/ground_truth_upper_bound/combined_sd_1_5/predictions/epoch_27_step_800.png"
    evaluate: True

lr:
  _target_: config.LearningRateConfig
  unet: 5e-5
  scale: True

lr_scheduler:
  _target_: config.LRSchedulerConfig
  scheduler_type: "constant"
  warmup_steps: 500
  num_cycles: 1
  power: 1.0

optimizer:
  _target_: config.OptimizerConfig
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1e-2
  adam_epsilon: 1e-08

dataset:
  _target_: config.DatasetConfig
  dataset_name: "uavid"
  dataset_path: "/teamspace/studios/this_studio/uavid"
  resolution: 512
  center_crop: True
  max_previous_frames: null
  oracle: True

dataloader:
  _target_: config.DataloaderConfig
  train_batch_size: 12
  val_batch_size: 4
  num_workers: 4

model:
  _target_: config.ModelConfig
  model_name: "lambdalabs/sd-image-variations-diffusers" # "runwayml/stable-diffusion-v1-5"
  model_revision: "v2.0"
  image_encoder_name: "lambdalabs/sd-image-variations-diffusers" # "openai/clip-vit-large-patch14"
  image_encoder_revision: "v2.0"
  train_unet: True
  train_control_net: False
  lora_rank: 4
  use_ip_adapter: False
  ip_adapter_scale: 0.8
  use_mapper: False
  use_lstm: False
  use_control_net: False

mapper:
  _target_: config.MapperConfig
  train: False

lstm:
  _target_: config.LSTMConfig
  train: False


gradient_accumulation_steps: 1
num_train_epochs: 350
max_train_steps: null
use_checkpoint: null # "/teamspace/studios/this_studio/outputs/fixed/ground_truth_upper_bound/2024-05-25__01-08-07/checkpoints/checkpoint_0"
checkpointing_steps: 750
checkpoints_total_limit: null
prediction_steps: 100
predictions_dir_name: "predictions"

max_grad_norm: 1.0

output_dir: "."
local_rank: -1

num_processes: 1

logging_dir_name: "logs"
allow_tf32: False
logger: "tensorboard"

overrode_max_train_steps: False
