hydra:
  job:
    chdir: True
  run:
    dir: outputs/fixed/ground_truth_upper_bound/${now:%Y-%m-%d__%H-%M-%S}

_target_: config.TrainerConfig

eval_script:
    _target_: config.EvalConfig
    images_path: "/teamspace/studios/this_studio/outputs/test/fixed/averaging/2024-05-25__03-48-51/checkpoint_12/guidance_2_0p7img2img_steps300/predictions/step_0.png"
    evaluate: True

mapper:
  _target_: config.MapperConfig
  in_channels: 768
  hidden_channels: [256, 768]
  norm_layer_type: "layernorm"
  activation_layer_type: "relu"
  inplace: null
  bias: True
  dropout: 0.2
  train: False

lstm:
  _target_: config.LSTMConfig
  input_size: 768
  hidden_size: 768
  num_layers: 1
  bias: True
  batch_first: False
  dropout: 0.2
  bidirectional: False
  proj_size: 0
  train: False

lr:
  _target_: config.LearningRateConfig
  unet: 1e-4
  controlnet: 2e-4
  mapper: 2e-4
  lstm: 4e-3
  scale: True

lr_scheduler:
  _target_: config.LRSchedulerConfig
  scheduler_type: "constant"
  warmup_steps: 500
  num_cycles: 1
  power: 1.0

optimizer:
  _target_: config.OptimizerConfig
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1e-2
  adam_epsilon: 1e-08

dataset:
  _target_: config.DatasetConfig
  dataset_name: "uavid"
  dataset_path: "/teamspace/studios/this_studio/uavid"
  resolution: 512
  center_crop: True
  max_previous_frames: null
  oracle: False

dataloader:
  _target_: config.DataloaderConfig
  train_batch_size: 6
  val_batch_size: 4
  num_workers: 4

model:
  _target_: config.ModelConfig
  model_name: "lambdalabs/sd-image-variations-diffusers" # "runwayml/stable-diffusion-v1-5"
  model_revision: "v2.0"
  image_encoder_name: "lambdalabs/sd-image-variations-diffusers" # "openai/clip-vit-large-patch14"
  image_encoder_revision: "v2.0"
  train_unet: True
  train_control_net: True
  use_control_net: True
  lora_rank: 4
  use_ip_adapter: False
  ip_adapter_scale: 0.8
  use_mapper: False
  use_lstm: False
  use_img2img_inference: False

gradient_accumulation_steps: 1
num_train_epochs: 350
max_train_steps: null
use_checkpoint: null # "/teamspace/studios/this_studio/outputs/fixed/ground_truth_upper_bound/2024-05-25__01-08-07/checkpoints/checkpoint_0"
checkpointing_steps: 750
checkpoints_total_limit: null
prediction_steps: 100
predictions_dir_name: "predictions"
use_custom_inference: False

max_grad_norm: 1.0

output_dir: "."
local_rank: -1

num_processes: 1

logging_dir_name: "logs"
allow_tf32: False
logger: "tensorboard"

overrode_max_train_steps: False